### ISSUE TITLE
Test the cursor position

### ISSUE THREAD

**Issue by NicolasWebDev** [LucHermitte/vim-UT#6]
Hi,

is there a way to test a script on a given mock file with a given cursor position and movements?

Thanks for the great work!

**Comment by LucHermitte** [comment]
Hi,

So far, I haven't done any work in that direction. Instead I've found vimrunner and see to integrate vim-ut and vimrunner: https://github.com/LucHermitte/vim-UT/blob/master/doc/rspec-integration.md

It's far from being perfect, but so far I'm happy with this solution.

You could find example of use in lh-brackets and lh-cpp tests: see https://github.com/LucHermitte/lh-cpp/blob/master/spec/spe_func_spec.rb#L301

**Comment by NicolasWebDev** [comment]
So vim-runner enables me to test the buffer content and stuff like that?

Thanks for your quick answer, I will have a look there then.

**Comment by LucHermitte** [comment]
With vim-ut, you can perfectly do things in a buffer and check its state (`:h getline()`). However, it can't be as neat as:

```
    set_buffer_contents <<-EOF
        instr1;
        instr2;
        instr3;
    EOF
    vim.normal("2gg")
    vim.feedkeys('µ\<esc>')
    assert_buffer_contents <<-EOF
        instr1;
        #if 0
        instr2;
        #else<++>
        #endif<++>
        instr3;
    EOF
```

The problem is that vim-UT is 100% VimL, and as far as I know, we cannot write 

```
:put << EOF
      instr1;
      instr2;
      instr3;
EOF
```

That's where solution like vimrunner are really interesting. Moreover, they are easy to integrate with travis. That's why I've provided a wrapper on top of vim-UT to use it from travis through vimrunner.
The downside is that the client-server mode has a few quirks and sometimes valid tests are failing for no good reason.

**Comment by NicolasWebDev** [comment]
Okay, so now we're talking ^^.

I have had a look at vimrunner, and it's perfect because I already program in Ruby.

So now my question: what does vim-UT brings over just vimrunner? Because if I understand well, vimrunner supports all the rspec expectations, no?

**Comment by LucHermitte** [comment]
Let's put aside that vim-UT is older and is what I've been using for ages ^^

vim-UT brings:
- the errors in the qf windows -- this is the main advantage of vim-UT over every other solution: the backtrace of failing tests and uncaught (vim) exceptions is displayed in the quickfix window. I use it to test my pure functions. I found it more practical to test lh-vim-lib functions through vim-UT. BTW, I don't leave vim.
- a neater syntax to test VimL functions IMO. Compare `AssertEqual('foobar', my#function#foobar())` to `expect(vim.echo('my#function#foobar()')).to eq "foobar"` (this is a simple one: no string is passed to `vim.echo`, no dictionary or list is manipulated)
- no side effect from `+clientserver` mode. There are a few synchronisation bugs lying around. More than once I had to introduce dummy sleeps in order to be sure vim buffers were updated before fetching their new state. vimrunner is not at fault here, but it suffers from its usage of the clientserver API.
- 100% VimL: it works perfectly everywhere vim runs. I had trouble to have vimrunner work correctly on my hybrid cygwin+gvim32 (and now gvim64) configuration.

Note that I also add a few helper functions missing in vimrunner. https://github.com/LucHermitte/vim-UT/tree/master/spec/support (I did also provide a definition for the missing `vim.runtime` function that behaves as VimL command somewhere -- in lh-brackets or lh-cpp may be. I'll have to check eventually)

Did you see https://github.com/LucHermitte/vim-UT/blob/master/doc/rspec-integration.md ?

**Comment by NicolasWebDev** [comment]
I think that your answer sums up quite nicely the advantages of vim-UT above vimrunner.

I think that you may want to include that in the introduction of your rspec-integration.md file, to make it maybe a bit clearer.

Actually I think that the biggest advantage is to write the tests in VimL. Indeed, for a plugin that is not ruby-related, I guess it is easier on contributors if it is pure VimL, abstracting away the ruby code needed for vimrunner.

For my current need I think I will stick with vimrunner, but as soon as I would like to test a non-ruby related plugin, then I will give your test suite a try ^^.

Many thanks for your help and your willingness to help!
